### ISSUE TITLE
Adding multiple images

### ISSUE THREAD

**Issue by pavelradvan** [pixelninja/media_library#4]
When I have section with media library field and allowed uploading multiple images, there is a problem with including them right after upload and selecting.
I click on adding images to entry of section. Than media library opens, so I upload images.
Those images I see in lower part of window and just check them and click on select.
After select images are in entry but not each individual bud every image is included six times or three times...it appears it is random how many times...
It is quite annoying to remove duplicates when there is 10 images and each of them is included six times....

When I use media library option from main backend menu and upload images it has another behavior.
It sometimes includes images right, but it is including them three times most of time.

When I am adding single image from already uploaded files it is OK.

![image](https://user-images.githubusercontent.com/1289011/90195601-2610f800-ddca-11ea-9350-8c01272f6574.png)
![image](https://user-images.githubusercontent.com/1289011/90195611-32955080-ddca-11ea-8487-60d27bc1dcf9.png)

**Comment by pixelninja** [comment]
Thanks @pavelradvan , it sounds like some events are being called multiple times. I will take a look as soon as I can,

**Comment by pixelninja** [comment]
Hi @pavelradvan this should be fixed now in the latest commit

**Comment by pavelradvan** [comment]
Hi i have tried your new version of extension with fix and updated in my customers new web site.
There is still same problem - even in adding only 1 picture

![image](https://user-images.githubusercontent.com/1289011/91046579-fad3a780-e618-11ea-9a97-b897b492bf64.png)

What do you want to know from me to solve problems?
PHPinfo is here:[https://hotelnabucco.com/phpinfo.php](url)

Pavel

**Comment by pixelninja** [comment]
Can you please make sure your cache is cleared, or test it in a new browser/private mode. If it's still doing it, can you please confirm the extension version number, symphony version number, and step by step instructions on how to replicate it?

**Comment by pavelradvan** [comment]
Hi,
I tried it on another website I have done about 2 weeks ago and now it is ok.
I also tried it in anonymous windows and it is OK now. So it is in clearing the cache of browser.
Is there any help of cache management extension in symphony ?
I need always to clean cache of browser ?

**Comment by pixelninja** [comment]
Yeah unfortunately there isn't any cache busting on Symphony admin assets currently.
