### ISSUE TITLE
Deleting images

### ISSUE THREAD

**Issue by pavelradvan** [pixelninja/media_library#5]
When I want to delete image or images in media library, dialog for confirmation hangs up.
I need to refresh page to get out - it is not doing anything when I click on OK or Storno...
When I use media library to delete previously already uploaded images, it works but sometimes it also hangs on dialog
![image](https://user-images.githubusercontent.com/1289011/90195832-cbc46700-ddca-11ea-83d4-844d2e28589f.png)
![image](https://user-images.githubusercontent.com/1289011/90195840-cff08480-ddca-11ea-84f9-3a203f17e09c.png)

**Comment by pixelninja** [comment]
Sounds like same issue as #4 , I will investigate

**Comment by pixelninja** [comment]
Hi @pavelradvan this should be fixed now in the latest commit
