### ISSUE TITLE
How to use with JIT Image Manipulation

### ISSUE THREAD

**Issue by jude86-7** [pixelninja/media_library#6]
In the data source the following is shown for the item value; /workspace/uploads/image_name.jpg

However I'm not sure how to get this working with JIT as it doesn't work with the 'workspace' directory named.

e.g. /image/1/200/0/{image/item} 
produces 
/image/1/200/0/workspace/uploads/image_name.jpg 
rather than the required 
/image/1/200/0/uploads/image_name.jpg

Many thanks

**Comment by pixelninja** [comment]
Ah ok, interesting. I don't use JIT so haven't had this issue before.

You could use XSLT to output the part of the string you need, i.e `substring-after('/workspace/uploads/image_name.jpg', '/workspace')` would output `/uploads/image_name.jpg`.

Or perhaps I could add a JIT friendly attribute in the XML output.

**Comment by jude86-7** [comment]
Thank you for replying so quickly, the substring works a treat, can't believe I didn't think of that workaround!
